name: 'maven_dm'
version: '1.0.0'
config-version: 2

profile: 'maven_dm'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  maven_dm:
    core:
      cubes:
        +materialized: view
      mart:
        +materialized: table
