maven_dm:
  target: prod
  outputs:
    prod:
      threads: 1
      type: postgres
      host: localhost
      port: 5432
      database: maven_dw
      schema: olap
      user: postgres
      pass: postgres
